[package]
name = "grafton-visca-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Procedural macros for the grafton-visca library"
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories = ["multimedia"]
keywords = ["ptz", "camera", "visca", "video", "macros"]
exclude = ["target/", ".gitignore", ".github/", ".vscode/"]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits", "fold"] }
quote = "1.0"
proc-macro2 = "1.0"
