//! Inquiry response decoders for VISCA protocol.
//!
//! The main dispatch logic is generated by the `define_inquiries!` macro in
//! [`crate::command::inquiry_registry`].  This module re-exports that dispatcher
//! and adds profile-aware decoding for responses that need coordinate-system
//! conversion (currently only `PanTiltPosition`).

use super::payload::{Nibbles, Payload};
use super::types::Response;
use crate::capabilities::{PanTilt, Profile};
use crate::command::inquiry_registry::InquiryKind;
use crate::command::InquiryData;
use crate::error::{format_payload_hex, Error};

// Re-export the registry's dispatch as the canonical decoder entry point.
pub(crate) use crate::command::inquiry_registry::dispatch;

/// Profile-aware decoder dispatch for responses that need coordinate conversion.
///
/// For `PanTiltPosition` inquiries the profile's `COORDINATE_SYSTEM` is used to
/// convert camera coordinates to logical coordinates.  All other inquiry kinds
/// are forwarded to the standard [`dispatch`] function.
pub(crate) fn dispatch_for<P: Profile + PanTilt>(
    kind: InquiryKind,
    payload: Payload<'_>,
) -> Result<Response, Error> {
    if kind == InquiryKind::PanTiltPosition {
        return decode_pan_tilt_position_for::<P>(payload);
    }

    dispatch(kind, payload)
}

/// Profile-aware decode for pan/tilt position inquiry responses.
///
/// Converts camera coordinates to logical coordinates using the profile's
/// coordinate system.
fn decode_pan_tilt_position_for<P: Profile + PanTilt>(
    payload: Payload<'_>,
) -> Result<Response, Error> {
    if payload.len() == 8 {
        let nibbles = Nibbles::<8>::try_from(payload)?;
        let pan_u16 = nibbles.u16_quad(0);
        let tilt_u16 = nibbles.u16_quad(4);

        let (pan, tilt) = P::COORDINATE_SYSTEM.convert_from_camera_coords(pan_u16, tilt_u16);

        Ok(Response::Inquiry(InquiryData::PanTiltPosition {
            pan,
            tilt,
        }))
    } else if payload.len() == 4 {
        tracing::warn!(
            "PanTiltPosition: Received compact format (4 bytes). Payload: {:02X?}. Treating as home position.",
            payload.as_slice()
        );
        let pan_u16 = if payload.len() >= 2 {
            ((payload.as_slice()[0] as u16) << 8) | (payload.as_slice()[1] as u16)
        } else {
            0x8000
        };
        let tilt_u16 = if payload.len() >= 4 {
            ((payload.as_slice()[2] as u16) << 8) | (payload.as_slice()[3] as u16)
        } else {
            0x8000
        };

        let (pan, tilt) = P::COORDINATE_SYSTEM.convert_from_camera_coords(pan_u16, tilt_u16);

        Ok(Response::Inquiry(InquiryData::PanTiltPosition {
            pan,
            tilt,
        }))
    } else {
        tracing::debug!(
            "PanTiltPosition: Payload length {} doesn't match pan/tilt format (expected 8 or 4 bytes)",
            payload.len()
        );
        Err(Error::DecoderNotFound {
            inquiry_kind: InquiryKind::PanTiltPosition,
            payload_hex: format_payload_hex(payload.as_slice()),
        })
    }
}

#[cfg(test)]
#[allow(clippy::panic)]
mod tests {
    use super::*;
    use crate::command::response::payload::Payload;

    /// Helper to dispatch a raw payload slice for a given inquiry kind.
    #[allow(clippy::unwrap_used)]
    fn decode(kind: InquiryKind, raw: &[u8]) -> Response {
        let payload = Payload::new(raw);
        dispatch(kind, payload).unwrap()
    }

    #[test]
    fn test_red_channel_g2_wire_format() {
        let resp = decode(InquiryKind::RedChannel, &[0x00, 0x00, 0x0D, 0x05]);
        match resp {
            Response::Inquiry(InquiryData::RedChannel { gain }) => assert_eq!(gain, 0xD5),
            other => panic!("unexpected response: {other:?}"),
        }
    }

    #[test]
    fn test_blue_channel_g2_wire_format() {
        let resp = decode(InquiryKind::BlueChannel, &[0x00, 0x00, 0x0B, 0x01]);
        match resp {
            Response::Inquiry(InquiryData::BlueChannel { gain }) => assert_eq!(gain, 0xB1),
            other => panic!("unexpected response: {other:?}"),
        }
    }

    #[test]
    fn test_color_temperature_g2_wire_format() {
        let resp = decode(InquiryKind::ColorTemperature, &[0x28]);
        match resp {
            Response::Inquiry(InquiryData::ColorTemperature { temperature }) => {
                assert_eq!(temperature, 0x28);
            }
            other => panic!("unexpected response: {other:?}"),
        }
    }

    #[test]
    fn test_red_tuning_g2_wire_format() {
        let resp = decode(InquiryKind::RedTuning, &[0x00, 0x00, 0x00, 0x0F]);
        match resp {
            Response::Inquiry(InquiryData::RedTuning { level }) => assert_eq!(level, 5),
            other => panic!("unexpected response: {other:?}"),
        }
    }

    #[test]
    fn test_blue_tuning_g2_wire_format() {
        let resp = decode(InquiryKind::BlueTuning, &[0x00, 0x00, 0x00, 0x0A]);
        match resp {
            Response::Inquiry(InquiryData::BlueTuning { level }) => assert_eq!(level, 0),
            other => panic!("unexpected response: {other:?}"),
        }
    }
}
