//! Declarative vocabulary for optional typed profile support.
//!
//! The callback pattern lets the enum, private bitset, serde names, public
//! marker traits, registry marker implementations, and contributor table all
//! expand from this one list. Keep profile membership in the built-in profile
//! registry; this file defines the vocabulary and its stable wire spelling.

macro_rules! typed_support_registry {
    ($callback:ident $(, $prefix:tt)*) => {
        $callback! {
            $($prefix)*
            [
                {
                    surface: DirectZoom,
                    marker: HasDirectZoom,
                    bit: 0,
                    wire: "direct-zoom",
                    area: "Zoom",
                    api: "Static gate for `camera.zoom().set_position`, `.set_normalized`, and `.set_normalized_in_domain`",
                    surface_doc: "Direct absolute zoom positioning.",
                    marker_doc: "Marker trait indicating support for direct absolute zoom positioning.",
                    diagnostic: "profile `{Self}` does not declare direct absolute zoom support",
                },
                {
                    surface: DigitalZoomToggle,
                    marker: HasDigitalZoomToggle,
                    bit: 1,
                    wire: "digital-zoom-toggle",
                    area: "Zoom",
                    api: "`camera.zoom().set_digital_zoom`",
                    surface_doc: "VISCA digital zoom enable/disable command.",
                    marker_doc: "Marker trait indicating support for the VISCA digital zoom on/off command.",
                    diagnostic: "profile `{Self}` does not declare VISCA digital zoom toggle support",
                },
                {
                    surface: DigitalZoomRange,
                    marker: HasDigitalZoomRange,
                    bit: 2,
                    wire: "digital-zoom-range",
                    area: "Zoom",
                    api: "`TypedSupportSet` runtime gate when `.set_normalized_in_domain(..., ZoomDomain::OpticalPlusDigital)` is chosen; also requires a documented digital maximum",
                    surface_doc: "Absolute zoom positions in the optical-plus-digital range.",
                    marker_doc: "Marker trait indicating support for absolute zoom positions beyond the optical range.",
                    diagnostic: "profile `{Self}` does not declare optical-plus-digital zoom range support",
                },
                {
                    surface: IrisControl,
                    marker: HasIrisControl,
                    bit: 3,
                    wire: "iris-control",
                    area: "Exposure",
                    api: "iris reset/up/down/direct control and `IrisInquiryControl` (`09 04 4B` position)",
                    surface_doc: "Standard iris controls and the `09 04 4B` iris-position inquiry.",
                    marker_doc: "Marker trait indicating support for standard iris control and position inquiry.",
                    diagnostic: "profile `{Self}` does not declare iris control support",
                },
                {
                    surface: OnePushFocus,
                    marker: HasOnePushFocus,
                    bit: 4,
                    wire: "one-push-focus",
                    area: "Focus",
                    api: "`OnePushFocusControl`",
                    surface_doc: "Standard one-push auto focus trigger.",
                    marker_doc: "Marker trait indicating support for standard one-push auto focus.",
                    diagnostic: "profile `{Self}` does not declare one-push focus support",
                },
                {
                    surface: PtzOpticsSnapFocus,
                    marker: HasPtzOpticsSnapFocus,
                    bit: 5,
                    wire: "ptz-optics-snap-focus",
                    area: "Focus",
                    api: "`SnapFocusControl`",
                    surface_doc: "PTZOptics snap focus command.",
                    marker_doc: "Marker trait indicating support for PTZOptics snap focus.",
                    diagnostic: "profile `{Self}` does not declare PTZOptics snap-focus support",
                },
                {
                    surface: FocusLock,
                    marker: HasFocusLock,
                    bit: 6,
                    wire: "focus-lock",
                    area: "Focus",
                    api: "focus-lock control",
                    surface_doc: "Focus lock command.",
                    marker_doc: "Marker trait indicating support for focus lock.",
                    diagnostic: "profile `{Self}` does not declare focus-lock support",
                },
                {
                    surface: PushAutoFocus,
                    marker: HasPushAutoFocus,
                    bit: 7,
                    wire: "push-auto-focus",
                    area: "Focus",
                    api: "Sony Push AF press/release control",
                    surface_doc: "Sony push auto focus command.",
                    marker_doc: "Marker trait indicating support for Sony Push AF.",
                    diagnostic: "profile `{Self}` does not declare Push AF support",
                },
                {
                    surface: FocusZone,
                    marker: HasFocusZone,
                    bit: 8,
                    wire: "focus-zone",
                    area: "Focus",
                    api: "focus-zone selection control",
                    surface_doc: "Focus-zone selection command.",
                    marker_doc: "Marker trait indicating support for focus-zone selection.",
                    diagnostic: "profile `{Self}` does not declare focus-zone support",
                },
                {
                    surface: AutoFocusSensitivity,
                    marker: HasAutoFocusSensitivity,
                    bit: 9,
                    wire: "auto-focus-sensitivity",
                    area: "Focus",
                    api: "AF sensitivity controls and inquiry",
                    surface_doc: "Auto-focus sensitivity control and inquiry.",
                    marker_doc: "Marker trait indicating support for auto-focus sensitivity adjustment.",
                    diagnostic: "profile `{Self}` does not declare auto-focus sensitivity support",
                },
                {
                    surface: FocusNearLimitInquiry,
                    marker: HasFocusNearLimitInquiry,
                    bit: 10,
                    wire: "focus-near-limit-inquiry",
                    area: "Focus",
                    api: "focus near-limit inquiry",
                    surface_doc: "Focus near-limit inquiry.",
                    marker_doc: "Marker trait indicating support for the focus near-limit inquiry.",
                    diagnostic: "profile `{Self}` does not declare focus near-limit inquiry support",
                },
                {
                    surface: BacklightCompensation,
                    marker: HasBacklightCompensation,
                    bit: 11,
                    wire: "backlight-compensation",
                    area: "Exposure",
                    api: "`BacklightCompensationControl` and backlight inquiry",
                    surface_doc: "Backlight compensation control and inquiry.",
                    marker_doc: "Marker trait indicating support for backlight compensation control and inquiry.",
                    diagnostic: "profile `{Self}` does not declare backlight compensation support",
                },
                {
                    surface: WideDynamicRange,
                    marker: HasWideDynamicRange,
                    bit: 12,
                    wire: "wide-dynamic-range",
                    area: "Exposure",
                    api: "`WideDynamicRangeControl` and dynamic-range inquiry",
                    surface_doc: "Wide dynamic range control and inquiry.",
                    marker_doc: "Marker trait indicating support for wide dynamic range control and inquiry.",
                    diagnostic: "profile `{Self}` does not declare wide dynamic range support",
                },
                {
                    surface: ExposureCompensation,
                    marker: HasExposureCompensation,
                    bit: 13,
                    wire: "exposure-compensation",
                    area: "Exposure",
                    api: "exposure-compensation controls and inquiries",
                    surface_doc: "Exposure compensation controls and inquiries.",
                    marker_doc: "Marker trait indicating support for exposure compensation.",
                    diagnostic: "profile `{Self}` does not declare exposure-compensation support",
                },
                {
                    surface: BrightnessControl,
                    marker: HasBrightnessControl,
                    bit: 14,
                    wire: "brightness-control",
                    area: "Exposure",
                    api: "exposure brightness controls and inquiry",
                    surface_doc: "Exposure brightness controls and inquiry.",
                    marker_doc: "Marker trait indicating support for VISCA exposure brightness control and inquiry.",
                    diagnostic: "profile `{Self}` does not declare exposure brightness support",
                },
                {
                    surface: OnePushWhiteBalance,
                    marker: HasOnePushWhiteBalance,
                    bit: 15,
                    wire: "one-push-white-balance",
                    area: "White balance",
                    api: "one-push white balance mode and trigger",
                    surface_doc: "One-push white balance mode and trigger.",
                    marker_doc: "Marker trait indicating support for one-push white balance mode and trigger.",
                    diagnostic: "profile `{Self}` does not declare one-push white-balance support",
                },
                {
                    surface: AutoTrackingWhiteBalance,
                    marker: HasAutoTrackingWhiteBalance,
                    bit: 16,
                    wire: "auto-tracking-white-balance",
                    area: "White balance",
                    api: "ATW white balance mode",
                    surface_doc: "Auto-tracking white balance mode.",
                    marker_doc: "Marker trait indicating support for auto-tracking white balance mode.",
                    diagnostic: "profile `{Self}` does not declare auto-tracking white-balance support",
                },
                {
                    surface: AutoWhiteBalanceSensitivity,
                    marker: HasAutoWhiteBalanceSensitivity,
                    bit: 17,
                    wire: "auto-white-balance-sensitivity",
                    area: "White balance",
                    api: "AWB sensitivity control",
                    surface_doc: "Auto white-balance sensitivity control.",
                    marker_doc: "Marker trait indicating support for auto white-balance sensitivity control.",
                    diagnostic: "profile `{Self}` does not declare auto white-balance sensitivity support",
                },
                {
                    surface: ColorTemperature,
                    marker: HasColorTemperature,
                    bit: 18,
                    wire: "color-temperature",
                    area: "Color",
                    api: "color-temperature mode, setters, and inquiry",
                    surface_doc: "Color temperature controls and inquiry.",
                    marker_doc: "Marker trait indicating support for color-temperature white balance control.",
                    diagnostic: "profile `{Self}` does not declare color-temperature support",
                },
                {
                    surface: RgbGain,
                    marker: HasRgbGain,
                    bit: 19,
                    wire: "rgb-gain",
                    area: "Color",
                    api: "red/blue gain controls and inquiries",
                    surface_doc: "Red/blue gain controls and inquiries.",
                    marker_doc: "Marker trait indicating support for manual red/blue gain control.",
                    diagnostic: "profile `{Self}` does not declare RGB gain support",
                },
                {
                    surface: RgbTuning,
                    marker: HasRgbTuning,
                    bit: 20,
                    wire: "rgb-tuning",
                    area: "Color",
                    api: "red/blue tuning controls and inquiries",
                    surface_doc: "Red/blue tuning controls and inquiries.",
                    marker_doc: "Marker trait indicating support for red/blue tuning control.",
                    diagnostic: "profile `{Self}` does not declare RGB tuning support",
                },
                {
                    surface: ImageFlip,
                    marker: HasImageFlip,
                    bit: 21,
                    wire: "image-flip",
                    area: "Image",
                    api: "vertical image flip control and inquiry",
                    surface_doc: "Vertical image flip control and inquiry.",
                    marker_doc: "Marker trait indicating support for vertical image flip control and inquiry.",
                    diagnostic: "profile `{Self}` does not declare image flip support",
                },
                {
                    surface: ImageMirror,
                    marker: HasImageMirror,
                    bit: 22,
                    wire: "image-mirror",
                    area: "Image",
                    api: "horizontal mirror control",
                    surface_doc: "Horizontal image mirror control.",
                    marker_doc: "Marker trait indicating support for horizontal image mirror control.",
                    diagnostic: "profile `{Self}` does not declare image mirror support",
                },
                {
                    surface: CombinedImageFlip,
                    marker: HasCombinedImageFlip,
                    bit: 23,
                    wire: "combined-image-flip",
                    area: "Image",
                    api: "combined flip-mode command",
                    surface_doc: "Combined image flip mode command.",
                    marker_doc: "Marker trait indicating support for the combined image flip mode command.",
                    diagnostic: "profile `{Self}` does not declare combined image flip mode support",
                },
                {
                    surface: ContrastControl,
                    marker: HasContrastControl,
                    bit: 24,
                    wire: "contrast-control",
                    area: "Image",
                    api: "contrast control and inquiry",
                    surface_doc: "Contrast control and inquiry.",
                    marker_doc: "Marker trait indicating support for contrast control and inquiry.",
                    diagnostic: "profile `{Self}` does not declare contrast control support",
                },
                {
                    surface: SharpnessControl,
                    marker: HasSharpnessControl,
                    bit: 25,
                    wire: "sharpness-control",
                    area: "Image",
                    api: "sharpness control and inquiry",
                    surface_doc: "Sharpness control and inquiry.",
                    marker_doc: "Marker trait indicating support for sharpness control and inquiry.",
                    diagnostic: "profile `{Self}` does not declare sharpness control support",
                },
                {
                    surface: SaturationControl,
                    marker: HasSaturationControl,
                    bit: 26,
                    wire: "saturation-control",
                    area: "Image",
                    api: "saturation control and inquiry",
                    surface_doc: "Saturation control and inquiry.",
                    marker_doc: "Marker trait indicating support for saturation control and inquiry.",
                    diagnostic: "profile `{Self}` does not declare saturation control support",
                },
                {
                    surface: HueControl,
                    marker: HasHueControl,
                    bit: 27,
                    wire: "hue-control",
                    area: "Image",
                    api: "hue control and inquiry",
                    surface_doc: "Hue control and inquiry.",
                    marker_doc: "Marker trait indicating support for hue control and inquiry.",
                    diagnostic: "profile `{Self}` does not declare hue control support",
                },
                {
                    surface: LuminanceControl,
                    marker: HasLuminanceControl,
                    bit: 28,
                    wire: "luminance-control",
                    area: "Image",
                    api: "luminance control and inquiry",
                    surface_doc: "Luminance control and inquiry.",
                    marker_doc: "Marker trait indicating support for luminance control and inquiry.",
                    diagnostic: "profile `{Self}` does not declare luminance control support",
                },
                {
                    surface: GammaControl,
                    marker: HasGammaControl,
                    bit: 29,
                    wire: "gamma-control",
                    area: "Image",
                    api: "gamma control and inquiry",
                    surface_doc: "Gamma control and inquiry.",
                    marker_doc: "Marker trait indicating support for gamma control and inquiry.",
                    diagnostic: "profile `{Self}` does not declare gamma control support",
                },
                {
                    surface: NoiseReduction2D,
                    marker: HasNoiseReduction2D,
                    bit: 30,
                    wire: "noise-reduction2-d",
                    area: "Image",
                    api: "2D noise-reduction mode and level inquiries",
                    surface_doc: "2D noise-reduction mode and level inquiries.",
                    marker_doc: "Marker trait indicating support for 2D noise-reduction mode and level inquiries.",
                    diagnostic: "profile `{Self}` does not declare 2D noise-reduction inquiry support",
                },
                {
                    surface: NoiseReduction3D,
                    marker: HasNoiseReduction3D,
                    bit: 31,
                    wire: "noise-reduction3-d",
                    area: "Image",
                    api: "3D noise-reduction level inquiry",
                    surface_doc: "3D noise-reduction level inquiry.",
                    marker_doc: "Marker trait indicating support for 3D noise-reduction level inquiry.",
                    diagnostic: "profile `{Self}` does not declare 3D noise-reduction inquiry support",
                },
                {
                    surface: PictureEffect,
                    marker: HasPictureEffect,
                    bit: 32,
                    wire: "picture-effect",
                    area: "Image",
                    api: "picture-effect control and inquiry",
                    surface_doc: "Picture-effect control and inquiry.",
                    marker_doc: "Marker trait indicating support for picture-effect control and inquiry.",
                    diagnostic: "profile `{Self}` does not declare picture-effect support",
                },
                {
                    surface: Tally,
                    marker: HasTally,
                    bit: 33,
                    wire: "tally",
                    area: "Tally",
                    api: "tally light controls and inquiries",
                    surface_doc: "Tally light controls and inquiries.",
                    marker_doc: "Marker trait indicating typed tally light API support.",
                    diagnostic: "profile `{Self}` does not declare typed tally-light support",
                },
                {
                    surface: DirectMenu,
                    marker: HasDirectMenuControl,
                    bit: 34,
                    wire: "direct-menu",
                    area: "Menu",
                    api: "direct menu controls",
                    surface_doc: "Direct menu controls.",
                    marker_doc: "Marker trait indicating support for direct menu controls.",
                    diagnostic: "profile `{Self}` does not declare direct menu-control support",
                },
                {
                    surface: NdFilter,
                    marker: HasNdFilter,
                    bit: 35,
                    wire: "nd-filter",
                    area: "ND filter",
                    api: "ND filter controls and inquiries",
                    surface_doc: "ND filter controls and inquiries.",
                    marker_doc: "Marker trait indicating typed ND filter API support.",
                    diagnostic: "profile `{Self}` does not declare typed ND filter support",
                },
                {
                    surface: VariableSpeed,
                    marker: HasVariableSpeed,
                    bit: 36,
                    wire: "variable-speed",
                    area: "Variable speed",
                    api: "variable speed mode controls",
                    surface_doc: "Variable speed mode controls.",
                    marker_doc: "Marker trait indicating typed variable speed API support.",
                    diagnostic: "profile `{Self}` does not declare typed variable-speed support",
                },
                {
                    surface: MotionSync,
                    marker: HasMotionSync,
                    bit: 37,
                    wire: "motion-sync",
                    area: "Motion Sync",
                    api: "Motion Sync controls and inquiries",
                    surface_doc: "Motion Sync controls and inquiries.",
                    marker_doc: "Marker trait indicating typed Motion Sync API support.",
                    diagnostic: "profile `{Self}` does not declare typed Motion Sync support",
                },
                {
                    surface: FocusZoneInquiry,
                    marker: HasFocusZoneInquiry,
                    bit: 38,
                    wire: "focus-zone-inquiry",
                    area: "Focus",
                    api: "focus-zone inquiry (independent of selection control)",
                    surface_doc: "Focus-zone inquiry, independently gated from selection control.",
                    marker_doc: "Marker trait indicating support for the focus-zone inquiry, independently of selection control.",
                    diagnostic: "profile `{Self}` does not declare focus-zone inquiry support",
                },
                {
                    surface: UsbAudio,
                    marker: HasUsbAudio,
                    bit: 39,
                    wire: "usb-audio",
                    area: "Streaming",
                    api: "USB audio control and inquiry",
                    surface_doc: "USB audio control and inquiry.",
                    marker_doc: "Marker trait indicating support for USB audio control and inquiry.",
                    diagnostic: "profile `{Self}` does not declare USB audio support",
                },
                {
                    surface: PtzOpticsAntiFlicker,
                    marker: HasPtzOpticsAntiFlicker,
                    bit: 40,
                    wire: "ptz-optics-anti-flicker",
                    area: "Exposure",
                    api: "PTZOptics anti-flicker control and inquiry",
                    surface_doc: "PTZOptics anti-flicker control and inquiry.",
                    marker_doc: "Marker trait indicating support for PTZOptics anti-flicker control and inquiry.",
                    diagnostic: "profile `{Self}` does not declare PTZOptics anti-flicker support",
                },
                {
                    surface: PtzOpticsSettingsSave,
                    marker: HasPtzOpticsSettingsSave,
                    bit: 41,
                    wire: "ptz-optics-settings-save",
                    area: "System",
                    api: "PTZOptics settings-save command",
                    surface_doc: "PTZOptics persistent-settings save command.",
                    marker_doc: "Marker trait indicating support for the PTZOptics settings-save command.",
                    diagnostic: "profile `{Self}` does not declare PTZOptics settings-save support",
                },
                {
                    surface: PtzOpticsPresetRecallSpeed,
                    marker: HasPtzOpticsPresetRecallSpeed,
                    bit: 42,
                    wire: "ptz-optics-preset-recall-speed",
                    area: "Presets",
                    api: "PTZOptics preset-recall speed control",
                    surface_doc: "PTZOptics preset-recall speed control.",
                    marker_doc: "Marker trait indicating support for PTZOptics preset-recall speed control.",
                    diagnostic: "profile `{Self}` does not declare PTZOptics preset-recall speed support",
                },
                {
                    surface: SonySpotlight,
                    marker: HasSonySpotlight,
                    bit: 43,
                    wire: "sony-spotlight",
                    area: "Exposure",
                    api: "Sony spotlight controls",
                    surface_doc: "Sony VISCA spotlight controls.",
                    marker_doc: "Marker trait indicating support for Sony VISCA spotlight controls.",
                    diagnostic: "profile `{Self}` does not declare Sony spotlight support",
                },
                {
                    surface: SonyAutoSlowShutter,
                    marker: HasSonyAutoSlowShutter,
                    bit: 44,
                    wire: "sony-auto-slow-shutter",
                    area: "Exposure",
                    api: "Sony automatic slow-shutter controls",
                    surface_doc: "Sony VISCA automatic slow-shutter controls.",
                    marker_doc: "Marker trait indicating support for Sony VISCA automatic slow-shutter controls.",
                    diagnostic: "profile `{Self}` does not declare Sony auto slow-shutter support",
                },
                {
                    surface: PtzOpticsMulticastStreaming,
                    marker: HasPtzOpticsMulticastStreaming,
                    bit: 45,
                    wire: "ptz-optics-multicast-streaming",
                    area: "Streaming",
                    api: "PTZOptics multicast-streaming controls",
                    surface_doc: "PTZOptics multicast-streaming controls.",
                    marker_doc: "Marker trait indicating support for PTZOptics multicast-streaming controls.",
                    diagnostic: "profile `{Self}` does not declare PTZOptics multicast-streaming support",
                },
                {
                    surface: PtzOpticsNdiQuality,
                    marker: HasPtzOpticsNdiQuality,
                    bit: 46,
                    wire: "ptz-optics-ndi-quality",
                    area: "Streaming",
                    api: "PTZOptics NDI-quality control",
                    surface_doc: "PTZOptics NDI-quality control.",
                    marker_doc: "Marker trait indicating support for PTZOptics NDI-quality control.",
                    diagnostic: "profile `{Self}` does not declare PTZOptics NDI-quality support",
                },
                {
                    surface: ExposureMode,
                    marker: HasExposureMode,
                    bit: 47,
                    wire: "exposure-mode",
                    area: "Exposure",
                    api: "shared `04 39` exposure-mode control and inquiry",
                    surface_doc: "Shared VISCA exposure-mode control and inquiry.",
                    marker_doc: "Marker trait indicating support for the shared VISCA exposure-mode command and inquiry family.",
                    diagnostic: "profile `{Self}` does not declare shared exposure-mode support",
                },
                {
                    surface: IrisControlInquiry,
                    marker: HasIrisControlInquiry,
                    bit: 48,
                    wire: "iris-control-inquiry",
                    area: "Exposure",
                    api: "`IrisControlInquiryControl` (`09 04 2B` auto/manual status)",
                    surface_doc: "Standard `09 04 2B` iris auto/manual status inquiry.",
                    marker_doc: "Marker trait indicating support for the standard `09 04 2B` iris auto/manual status inquiry.",
                    diagnostic: "profile `{Self}` does not declare iris control-status inquiry support",
                },
                {
                    surface: NoiseReduction2DControl,
                    marker: HasNoiseReduction2DControl,
                    bit: 49,
                    wire: "noise-reduction2-d-control",
                    area: "Image",
                    api: "2D noise-reduction mode/level controls and disable",
                    surface_doc: "2D noise-reduction mode and level controls, independently gated from inquiries.",
                    marker_doc: "Marker trait indicating support for 2D noise-reduction mode and level controls.",
                    diagnostic: "profile `{Self}` does not declare 2D noise-reduction control support",
                },
                {
                    surface: NoiseReduction3DControl,
                    marker: HasNoiseReduction3DControl,
                    bit: 50,
                    wire: "noise-reduction3-d-control",
                    area: "Image",
                    api: "3D noise-reduction level control and disable",
                    surface_doc: "3D noise-reduction level controls, independently gated from inquiries.",
                    marker_doc: "Marker trait indicating support for 3D noise-reduction level controls.",
                    diagnostic: "profile `{Self}` does not declare 3D noise-reduction control support",
                },
                {
                    surface: ImageFreeze,
                    marker: HasImageFreeze,
                    bit: 51,
                    wire: "image-freeze",
                    area: "Image",
                    api: "image-freeze control",
                    surface_doc: "Image-freeze control, available only to explicitly validated profiles.",
                    marker_doc: "Marker trait indicating explicitly validated image-freeze support.",
                    diagnostic: "profile `{Self}` does not declare validated image-freeze support",
                },
                {
                    surface: DefogLevel,
                    marker: HasDefogLevel,
                    bit: 52,
                    wire: "defog-level",
                    area: "Image",
                    api: "vendor defog-level inquiry",
                    surface_doc: "Vendor defog-level inquiry, available only to explicitly validated profiles.",
                    marker_doc: "Marker trait indicating explicitly validated defog-level inquiry support.",
                    diagnostic: "profile `{Self}` does not declare validated defog-level inquiry support",
                },
                {
                    surface: TallyBrightness,
                    marker: HasTallyBrightness,
                    bit: 53,
                    wire: "tally-brightness",
                    area: "Tally",
                    api: "extended tally-brightness commands",
                    surface_doc: "Extended tally-brightness commands, independently gated from Sony red/green tally.",
                    marker_doc: "Marker trait indicating explicitly validated tally-brightness support.",
                    diagnostic: "profile `{Self}` does not declare validated tally-brightness support",
                },
                {
                    surface: PtzOpticsTally,
                    marker: HasPtzOpticsTally,
                    bit: 54,
                    wire: "ptz-optics-tally",
                    area: "Tally",
                    api: "PTZOptics packed status, mode, and auto-adjust tally family",
                    surface_doc: "PTZOptics tally extensions, independently gated from Sony red/green tally.",
                    marker_doc: "Marker trait indicating hardware-validated PTZOptics tally-extension support.",
                    diagnostic: "profile `{Self}` does not declare validated PTZOptics tally-extension support",
                },
            ]
        }
    };
}

pub(crate) use typed_support_registry;
