// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Blue gain value for white balance adjustment.
 */
export type BlueChannel = number;
