// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Brightness level for direct brightness control.
 */
export type BrightnessLevel = number;
