// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Broadcast domain setting affecting video output standards.
 *
 * This setting may affect video timing, color space, and other
 * broadcast-related parameters. The specific meaning depends on
 * the camera model.
 *
 * Valid range: Typically 0 to 3
 */
export type BroadcastDomain = number;
