// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Color temperature value for white balance control.
 */
export type ColorTemp = number;
