// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defog processing level for improving visibility in foggy or hazy conditions.
 *
 * Valid range: 0 to 5 (0x00 to 0x05)
 * Higher values apply stronger defog processing.
 */
export type DefogLevel = number;
