// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dynamic range level for wide dynamic range control.
 */
export type DynamicRangeLevel = number;
