// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exposure compensation position value (high-resolution EV adjustment).
 *
 * This is a higher-resolution representation of exposure compensation
 * compared to ExposureCompensationLevel. The actual range and mapping
 * to EV values depends on the camera model.
 *
 * Valid range: Typically 0 to 0x0E (0 to 14)
 */
export type ExposureCompensationPosition = number;
