// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exposure compensation level (-7 to +7).
 *
 * Valid range: -7 to +7.
 */
export type ExposureCompensationLevel = number;
