// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Focus speed value for camera focus control.
 *
 * Valid range: 0 to 7, where 0 is the slowest and 7 is the fastest.
 * This type provides the standard focus speed control for VISCA cameras.
 */
export type FocusSpeed = number;
