// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Variable focus speed.
 *
 * Valid range: 0 to 7 where 0 is the slowest and 7 is the fastest.
 */
export type FocusSpeed = number;
