// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Focus position value for direct focus control.
 *
 * This is a simple newtype wrapper around the raw VISCA focus position value.
 * The focus position range varies by camera model:
 * - PTZOptics cameras: typically 0x0000-0xFFFF
 * - Sony cameras: typically 0x1000-0xF000
 *
 * For profile-specific validation and normalization, use the [`FocusExt`] trait
 * methods which respect each camera profile's actual limits.
 *
 * [`FocusExt`]: crate::capabilities::focus::FocusExt
 */
export type FocusPosition = number;
