// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * F-stop values for iris control.
 *
 * Standard VISCA F-stop values from `Closed` (no light) to `F1_8` (widest opening).
 * These correspond to typical camera aperture settings. Lower numbers mean wider
 * aperture (more light).
 */
export type FStop =
  | "Closed"
  | "F11"
  | "F9_6"
  | "F8"
  | "F6_8"
  | "F5_6"
  | "F4_8"
  | "F4"
  | "F3_4"
  | "F2_8"
  | "F2_4"
  | "F2"
  | "F1_8";
