// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Gain values for PtzOptics G2 cameras.
 */
export type G2Gain =
  | "gain0d_b"
  | "gain3d_b"
  | "gain6d_b"
  | "gain9d_b"
  | "gain12d_b"
  | "gain15d_b"
  | "gain18d_b"
  | "gain21d_b"
  | "gain24d_b";
