// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Luminance level for brightness adjustment.
 */
export type LuminanceLevel = number;
