// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Motion sync speed value for synchronized camera movements.
 *
 * Valid range: 1 to 24 (0x01 to 0x18)
 * Used with PtzOptics cameras to control the speed of synchronized
 * pan, tilt, and zoom movements during preset recalls.
 */
export type MotionSyncSpeed = number;
