// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ND filter preset selection for cameras with multiple ND filter configurations.
 *
 * This allows switching between different saved ND filter settings
 * on cameras that support preset ND configurations.
 *
 * Valid range: Typically 0 to 3
 */
export type NdFilterPreset = number;
