// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ndi streaming quality settings for PtzOptics cameras.
 *
 * Controls the bandwidth and quality of Ndi HX video streaming.
 * This is a vendor-specific feature for PtzOptics Ndi cameras.
 */
export type NdiQuality = "high" | "medium" | "low" | "off";
