// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-friendly noise reduction strength levels for VISCA cameras.
 *
 * Provides intuitive strength levels that are automatically converted to the
 * appropriate VISCA values for 2D and 3D noise reduction commands. Note that
 * the `Off` variant cannot be used with noise reduction commands as VISCA
 * requires a minimum level (level 1 = minimal).
 */
export type NoiseReductionStrength =
  | "off"
  | "minimal"
  | "light"
  | "medium"
  | "strong"
  | "maximum";
