// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pan speed value for horizontal camera movement speed.
 */
export type PanSpeed = number;
