// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Corner position for pan/tilt limit setting.
 *
 * Specifies which corner of the movement range to set as a limit.
 */
export type PanTiltLimitCorner =
  | "down_left"
  | "down_right"
  | "up_left"
  | "up_right";
