// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Direction for pan/tilt movement commands.
 *
 * Represents the 8 directional movements plus stop.
 */
export type PanTiltDirection =
  | "up"
  | "down"
  | "left"
  | "right"
  | "up_left"
  | "up_right"
  | "down_left"
  | "down_right"
  | "stop";
