// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preset number with validation.
 *
 * Valid range: 0 to 255 (0x00 to 0xFF).
 * Note: Actual valid range depends on camera model:
 * - PtzOptics G2: 0-89
 * - PtzOptics G3: 0-255
 * - Sony FR7: 0-255
 * - Sony EVI-H100: 0-6
 * Camera-specific validation is performed when sending commands.
 */
export type PresetNumber = number;
