// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Profile group for runtime polymorphism and profile dispatch.
 *
 * Groups camera profiles by their protocol compatibility and behavioral characteristics.
 * This enables runtime profile selection without requiring separate implementations
 * for each profile variant.
 *
 * # Example
 *
 * ```
 * use grafton_visca::camera::profiles::{ProfileId, ProfileGroup};
 *
 * let profile = ProfileId::SonyFr7;
 * let group = profile.profile_group();
 * assert_eq!(group, ProfileGroup::SonyProfessional);
 * ```
 */
export type ProfileGroup =
  | "generic-visca"
  | "ptz-optics-g2"
  | "sony-professional";
