// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable camera profile identifier.
 *
 * This enum provides a serializable way to identify camera profiles for use in
 * configuration files, APIs, and RPC interfaces. Unlike the zero-sized profile
 * marker types (`PtzOpticsG2`, `SonyFR7`, etc.), this enum can be serialized
 * and deserialized with serde.
 *
 * # Example
 *
 * ```
 * # #[cfg(feature = "serde")] {
 * use grafton_visca::camera::profiles::ProfileId;
 *
 * // Serialize to JSON
 * let profile = ProfileId::PtzOpticsG2;
 * let json = serde_json::to_string(&profile).unwrap();
 * assert_eq!(json, "\"ptz-optics-g2\"");
 *
 * // Deserialize from JSON
 * let profile: ProfileId = serde_json::from_str("\"sony-fr7\"").unwrap();
 * assert_eq!(profile, ProfileId::SonyFr7);
 * # }
 * ```
 */
export type ProfileId =
  | "ptz-optics-g2"
  | "ptz-optics-g3"
  | "ptzoptics-30x"
  | "sony-fr7"
  | "sony-brch900"
  | "sony-evih100"
  | "sony-brc300"
  | "nearus-brc300"
  | "generic-visca";
