// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Red tuning value for fine white balance adjustment.
 */
export type RedTuning = number;
