// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sharpness level for direct sharpness control.
 */
export type SharpnessLevel = number;
