// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shutter speed value for direct shutter control.
 */
export type ShutterSpeed = number;
