// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-friendly speed level abstraction for camera movements.
 *
 * Provides predefined speed combinations that work well across different
 * camera movement types (pan, tilt, zoom, focus) based on VISCA protocol ranges.
 * The variants range from `Slowest` (most precise) to `Fastest` (maximum speed).
 */
export type SpeedLevel = "slowest" | "slow" | "medium" | "fast" | "fastest";
