// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transport configuration options.
 */
export type TransportOptions = {
  "type": "TCP";
  /**
   * Host:port string (e.g., "192.168.0.110:5678")
   */
  address: string;
} | {
  "type": "UDP";
  /**
   * Host:port string (e.g., "192.168.0.110:1259")
   */
  address: string;
} | {
  "type": "Serial";
  /**
   * Serial port path (e.g., "/dev/ttyUSB0")
   */
  port: string;
  /**
   * Baud rate (default: 9600)
   */
  baud_rate: number;
} | { "type": "Custom" };
