// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Variable speed mode setting for Sony FR7.
 */
export type VariableSpeedMode = "standard24" | "fine50";
