// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Zoom position value for direct zoom control.
 */
export type ZoomPosition = number;
