// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Zoom speed value for camera zoom control.
 *
 * Valid range: 0 to 7, where 0 is the slowest and 7 is the fastest.
 * This type provides the standard zoom speed control for VISCA cameras.
 */
export type ZoomSpeed = number;
